import os
from dotenv import load_dotenv
load_dotenv()

# Enable LangSmith tracing
os.environ["LANGCHAIN_TRACING_V2"] = "true"
os.environ["LANGCHAIN_PROJECT"] = "real-estate-agent-eval"

os.environ["PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION"] = "python"
os.environ["USE_TF"] = "0"
os.environ["USE_TORCH"] = "1"

import streamlit as st

try:
    __import__('pysqlite3')
    import sys
    sys.modules['sqlite3'] = sys.modules.pop('pysqlite3')
except ImportError:
    pass

from langchain_community.callbacks.streamlit import StreamlitCallbackHandler
from langchain_core.messages import HumanMessage, AIMessage
from agent import SQLAgent

st.set_page_config(page_title="Real Estate AI Agent", page_icon="🏡", layout="wide")

# Sidebar for Database Schema and API Key
with st.sidebar:
    st.title("🏡 Real Estate Database")
    
    api_key_input = st.text_input("Enter your Gemini API Key", type="password")
    if api_key_input:
        os.environ["GEMINI_API_KEY"] = api_key_input
        
    working_models = [
        "gemini-2.5-flash",
        "gemini-1.5-pro",
        "gemini-2.5-flash",
        "gemini-2.5-pro",
        "gemini-pro"
    ]
    
    st.divider()
    st.subheader("Model Selection")
    
    selected_model = st.selectbox("Select Model", working_models)
    
    # If the user selects a new model, re-initialize the agent
    if "selected_model" not in st.session_state or st.session_state.selected_model != selected_model:
        st.session_state.selected_model = selected_model
        if "agent" in st.session_state:
            del st.session_state.agent
            
    st.divider()
    
    st.subheader("Database Context")
    if "agent" in st.session_state:
        st.code(st.session_state.agent.get_schema_string(), language='sql')
    else:
        st.write("Enter API Key/Token to load schema...")
        
    st.divider()
    st.subheader("Observability & Metrics")
    st.link_button("📈 Open LangSmith Dashboard", "https://smith.langchain.com/o/default/projects/p/real-estate-agent-eval")
    
    if os.path.exists("evaluation_results.csv"):
        if st.button("📊 Toggle Ragas Report"):
            st.session_state.show_eval = not st.session_state.get("show_eval", False)

# Main layout
st.title("🏡 Autonomous Real Estate AI Agent")

st.markdown("""
**A Hybrid Agentic System powered by LangGraph, Schema Introspection, and RAG.**

This AI bridges the gap between natural language, the massive **Ames Housing database**, and **local municipal zoning and tax laws**. Ask it a complex property or legal question, and watch the Supervisor node autonomously route the task to the SQL Expert or the RAG Expert in real-time!
""")



st.divider()

if st.session_state.get("show_eval", False) and os.path.exists("evaluation_results.csv"):
    st.subheader("📊 Ragas Evaluation Metrics")
    st.caption("Auto-generated by `evaluate.py`. Scores range from 0.0 to 1.0 (Higher is better).")
    import pandas as pd
    df = pd.read_csv("evaluation_results.csv")
    st.dataframe(df, use_container_width=True)
    st.divider()

st.write("### Ask the Database a Question")
st.caption("Ask questions about property sales, lot areas, tax rates, and zoning codes in plain English.")

# Check API key
if not os.environ.get("GEMINI_API_KEY"):
    st.warning("Please enter your Gemini API Key in the sidebar to start chatting.", icon="⚠️")
    st.stop()

# Initialize Agent
if "agent" not in st.session_state:
    try:
        with st.spinner("Connecting to Real Estate database and compiling LangGraph..."):
            st.session_state.agent = SQLAgent(
                model_name=st.session_state.get('selected_model', 'gemini-2.5-flash')
            )
        st.rerun() # Refresh so the sidebar gets the schema
    except Exception as e:
        st.error(f"Failed to initialize agent: {e}")
        st.stop()

# Initialize chat session
if "messages" not in st.session_state:
    st.session_state["messages"] = [
        {"role": "assistant", "content": "Hello! I am a Hybrid Real Estate AI Agent. I can query the property database and look up Ames zoning rules. What would you like to know?"}
    ]

# Display chat messages
for msg in st.session_state.messages:
    st.chat_message(msg["role"]).write(msg["content"])

if prompt := st.chat_input(placeholder="e.g. What is the average lot area for RL zoned homes?"):
    st.session_state.messages.append({"role": "user", "content": prompt})
    st.chat_message("user").write(prompt)

    with st.chat_message("assistant"):
        try:
            with st.status("Agent Thinking...", expanded=True) as status:
                final_answer = ""
                
                # Stream events from LangGraph
                for event in st.session_state.agent.agent_executor.stream({"messages": [HumanMessage(content=prompt)]}):
                    for node_name, node_state in event.items():
                        st.write(f"🟢 **Node executed:** `{node_name}`")
                        
                        if node_name == "sql_expert" and "sql_query" in node_state:
                            st.code(node_state["sql_query"], language="sql")
                        elif node_name == "execute_sql" and "sql_result" in node_state:
                            st.markdown("**Database Result:**")
                            st.code(node_state["sql_result"])
                        elif node_name == "rag_expert":
                            st.info("🔍 Scanned Knowledge Base for Policies.")
                            
                        # Check if this node added messages to the state
                        if "messages" in node_state and len(node_state["messages"]) > 0:
                            last_msg = node_state["messages"][-1]
                            if isinstance(last_msg, AIMessage):
                                final_answer = last_msg.content
                
                status.update(label="Complete", state="complete", expanded=False)
                
            if not final_answer:
                final_answer = "I'm sorry, I couldn't process that request."
                
            st.write(final_answer)
            st.session_state.messages.append({"role": "assistant", "content": final_answer})
            
        except Exception as e:
            st.error(f"An error occurred: {e}")
